export const prodUrlConstants = {
  // MAIN ENDPOINT
  MAIN_ENDPOINT: process.env.REACT_APP_BACKEND_URL,

  // AUTHENTICATION ENDPOINTS
  LOGIN_ENDPOINT: process.env.REACT_APP_BACKEND_URL + "/login",
  SIGN_UP_ENDPOINT: process.env.REACT_APP_BACKEND_URL + "/signup",

  // SUSCRIBER ENDPOINTS
  SUSCRIBE_ENDPOINT: process.env.REACT_APP_BACKEND_URL + "/suscribe",
  UNSUSCRIBE_ENDPOINT: process.env.REACT_APP_BACKEND_URL + "/delete/:",
  GET_SUSCRIBERS_ENDPOINT: process.env.REACT_APP_BACKEND_URL + "/suscribers",

  // UPLOAD ENDPOINTS
  UPLOAD_ENDPOINT: process.env.REACT_APP_BACKEND_URL + "/uploads",
  GET_FILES_ENDPOINT: process.env.REACT_APP_BACKEND_URL + "/files",

  // DASHBOARD ENDPOINT
  DASHBOARD_ENDPOINT: process.env.REACT_APP_BACKEND_URL + "/dashboard",

  // LOGOUT ENDPOINT
  LOGOUT_ENDPOINT: process.env.REACT_APP_BACKEND_URL + "/logout",

  // AUTO LOGIN ENDPOINT
  AUTO_LOGIN_ENDPOINT: process.env.REACT_APP_BACKEND_URL + "/autoLogin",
};
