export const prodUrlConstants = {
  // MAIN ENDPOINT
  MAIN_ENDPOINT: `${REACT_BACKEND_URL}`,

  // AUTHENTICATION ENDPOINTS
  LOGIN_ENDPOINT: `${REACT_BACKEND_URL}/login`,
  SIGN_UP_ENDPOINT: `${REACT_BACKEND_URL}/signup`,

  // SUSCRIBER ENDPOINTS
  SUSCRIBE_ENDPOINT: `${REACT_BACKEND_URL}/suscribe`,
  UNSUSCRIBE_ENDPOINT: `${REACT_BACKEND_URL}/delete/:`,
  GET_SUSCRIBERS_ENDPOINT: `${REACT_BACKEND_URL}/suscribers`,

  // UPLOAD ENDPOINTS
  UPLOAD_ENDPOINT: `${REACT_BACKEND_URL}/uploads`,

  // DASHBOARD ENDPOINT
  DASHBOARD_ENDPOINT: `${REACT_BACKEND_URL}/dashboard"`,

  // LOGOUT ENDPOINT
  LOGOUT_ENDPOINT: `${REACT_BACKEND_URL}/logout`,

  // AUTO LOGIN ENDPOINT
  AUTO_LOGIN_ENDPOINT: `${REACT_BACKEND_URL}/autoLogin`,
};
